apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deploy
  namespace: eks-getquote-app
  labels:
    name: frontend-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: frontend-app-pod
  template:
    metadata:
      name: frontend-app-pod
      labels:
        name: frontend-app-pod
    spec:
      containers:
        - name: frontend-app-container
          resources:
          image: grahesht/jenkins_images:v1
          env:
          - name: API_GATEWAY
            value: http://localhost
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service
  labels:
    name: frontend-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: frontend-app-deploy