apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service
  labels:
    name: frontend-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    name: frontend-app-pod